### ISSUE TITLE
RequestLoggingFilter 질문

### ISSUE THREAD

**Issue by swdevsw98** [DaITssu/daitssu-api#18]
## Issue

- RequestLoggingFilter 사용시 포스트맨으로 값을 못넣음

## Description

- 현재는 주석처리하고 진행하였음

## Screenshot
![image](https://github.com/DaITssu/daitssu-api/assets/102571918/a3012420-2907-4350-bb85-a36a6aca4f6d)
![image](https://github.com/DaITssu/daitssu-api/assets/102571918/4b787c8c-7fa5-4428-a83f-c7dd2c180cf1)

**Comment by kkanggu** [comment]
Body가 잘 넘어가는지는 확인을 안 했었네요.
해당 이슈 hotfix로 해결하였습니다. #19 에서 확인 가능합니다.
