### ISSUE TITLE
[백엔드] 로그인 로직 구현

### ISSUE THREAD

**Issue by HwanGonJang** [DaITssu/daitssu-api#35]

**Comment by HwanGonJang** [comment]
* 유세인트 로그인과 우리 서버의 로그인을 연동하는 과정이 매우 복잡하고 스프링 부트와 코틀린 스택으로 구현하기 어려운 부분이 많다는 생각이 들었어요
* 로그인을 파이썬 팀에서 처리하고 저희 메인 서버에서는 검증을 위해 사용하는 게 좋아보입니다

**Comment by kkanggu** [comment]
저번에 정리한 문서에서 변화가 없어서 저희한테 뭘 원하는지 판단이 불가능합니다.
그렇다고 저기서 정리해준 소스를 읽고 이해해야 한다면 저희가 할 필요 없다고 생각합니다.

1. 정보 제대로 넘겨주는거 아니면 로그인 이미 완료되었다고 가정하고 진행
2. 정보 및 필요한 프로세스를 제대로 넘겨주어 서버에서 처리

솔직히 1번이 편하긴 한데, 로그인 처리를 파이썬에서 진행하면 람다로 하기에는 cold start 때문에 느릴 것 같고. 별도로 로그인 전용으로 파이썬을 띄우기는 투머치인것 같습니다.
