### ISSUE TITLE
[마이페이지] 학적 정보 조회

### ISSUE THREAD

**Issue by HwanGonJang** [DaITssu/daitssu-api#76]
![image](https://github.com/DaITssu/daitssu-api/assets/69834729/bc2e3080-d6e8-42e4-94b5-c930e78d7074)

**Comment by JooHui-void** [comment]
@HwanGonJang  이부분 한구님이 만드신 getUser로 이미 처리가 되는 듯 합니다
![image](https://github.com/DaITssu/daitssu-api/assets/69834729/9325a5e8-db5f-4866-8561-d79738de09ee)
혹시 위에 이미지조회까지 가져와야하는 건지 궁금합니다

**Comment by HwanGonJang** [comment]
아하 확인했습니다~ 이미지는 일단 나중에 하죠
